### ISSUE TITLE
Simplify using `kubectl debug`?

### ISSUE THREAD

**Issue by marcosnils** [MartinHeinz/remote-debug-python-kubernetes#1]
Hey Martin, just finished reading your article. Thx for taking the time to write these things as always.

Since I couldn't find a way to left a comment in your blog, just wanted to share here that unless I'm missing something, it should be possible to simplify this example by leveraging the `kubectl debug` command line. ref: https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#ephemeral-container

cheers!

**Comment by MartinHeinz** [comment]
Hi, you have to set `securityContext` for the debugger container to be able to attach to application process. It's not possible to set container overrides with `kubectl debug` like with `kubectl run` so the only option is to use `PATCH` request.
